### ISSUE TITLE
OpenCV 자체 병렬화 기능

### ISSUE THREAD

**Issue by LazoYoung** [Invidam/image_convolution#2]
https://github.com/Invidam/image_convolution/blob/d26c643b433f0dcb8ab7eaabc2b8341b3686b74a/Calculator.cpp#L14

[OpenCV 문서](https://docs.opencv.org/4.9.0/d3/d63/classcv_1_1Mat.html#a952ef1a85d70a510240cb645a90efc0d)에 따르면 `Mat::forEach()` 메소드는 콜백 연산을 자체적으로 병렬처리하도록 구현해놓은 듯 한데, `#pragma omp parallel for` 지시어가 필요한지 궁금합니다. 만약 필요없다면 OpenMP를 안 쓰게 되는건데 과제 요구사항에 맞추려면 다른 함수를 써야될지도 모르겠네요

**Comment by Invidam** [comment]
openmp가 잘 동작하는지 테스트해보려고 넣어본거였는데

설명이 부족했네요..ㅠ

**Comment by LazoYoung** [comment]
아하 저거는 예시 코드였군요. 확인했습니다
